name: 'Docker Documentation Generator'
description: 'Automatically generate README documentation from Dockerfiles using dock-docs'
author: 'northcutted'
branding:
  icon: 'file-text'
  color: 'blue'

inputs:
  version:
    description: 'Version of dock-docs to use (e.g., v1.0.0). Defaults to latest.'
    default: 'latest'
    required: false
  
  # --- Configuration Inputs ---
  config:
    description: 'Path to configuration file. Enables YAML Mode if present.'
    default: 'dock-docs.yaml'
    required: false
  output:
    description: 'Output file path.'
    default: 'README.md'
    required: false
  
  # --- Boolean Flags ---
  dry-run:
    description: 'Print output to stdout instead of modifying files.'
    default: 'false'
    required: false
  nomoji:
    description: 'Disable emojis in the output.'
    default: 'false'
    required: false
  ignore-errors:
    description: 'Ignore analysis errors and continue generation.'
    default: 'false'
    required: false
  verbose:
    description: 'Enable verbose logging for debugging.'
    default: 'false'
    required: false

  # --- CLI Mode Inputs (Mutually exclusive with config usually) ---
  file:
    description: 'Path to Dockerfile (CLI Mode only).'
    required: false
  image:
    description: 'Docker image tag to analyze (CLI Mode only).'
    required: false

runs:
  using: "composite"
  steps:
    # 1. Setup Tool Cache
    - name: Setup Tool Cache
      shell: bash
      run: |
        TOOL_DIR="$HOME/.dock-docs/bin"
        mkdir -p "$TOOL_DIR"
        echo "$TOOL_DIR" >> $GITHUB_PATH

    # 2. Install Dependencies (Syft, Grype, Dive)
    - name: Install Dependencies
      shell: bash
      run: |
        TOOL_DIR="$HOME/.dock-docs/bin"
        
        # Install Syft & Grype
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b "$TOOL_DIR"
        curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b "$TOOL_DIR"

        # Install Dive (Architecture Detection)
        DIVE_VERSION="0.13.1"
        if [ "${{ runner.arch }}" = "ARM64" ]; then
           DIVE_ARCH="linux_arm64"
        else
           DIVE_ARCH="linux_amd64"
        fi
        
        curl -sL "https://github.com/wagoodman/dive/releases/download/v${DIVE_VERSION}/dive_${DIVE_VERSION}_${DIVE_ARCH}.tar.gz" \
          | tar xz -C "$TOOL_DIR" dive

    # 3. Install dock-docs
    - name: Install dock-docs
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        TOOL_DIR="$HOME/.dock-docs/bin"
        
        # Map GitHub Runner OS/Arch to GoReleaser naming convention
        OS_NAME=$(uname -s) # Linux, Darwin
        if [ "${{ runner.arch }}" = "ARM64" ]; then
          ARCH_NAME="arm64"
        else
          ARCH_NAME="x86_64"
        fi

        # Construct asset pattern (e.g., *_Linux_x86_64.tar.gz)
        ASSET_PATTERN="*_${OS_NAME}_${ARCH_NAME}.tar.gz"
        
        # Download via GH CLI
        if [ "${{ inputs.version }}" = "latest" ]; then
           gh release download --repo northcutted/dock-docs --pattern "$ASSET_PATTERN" --output "$TOOL_DIR/dock-docs.tar.gz" --clobber
        else
           gh release download ${{ inputs.version }} --repo northcutted/dock-docs --pattern "$ASSET_PATTERN" --output "$TOOL_DIR/dock-docs.tar.gz" --clobber
        fi

        # Extract
        tar -xzf "$TOOL_DIR/dock-docs.tar.gz" -C "$TOOL_DIR" dock-docs
        rm "$TOOL_DIR/dock-docs.tar.gz"
        chmod +x "$TOOL_DIR/dock-docs"

    # 4. Run dock-docs with all flags
    - name: Run dock-docs
      shell: bash
      run: |
        # Build arguments array dynamically
        CMD_ARGS=()

        # Always add output
        CMD_ARGS+=("--output" "${{ inputs.output }}")

        # YAML Mode: Only add if input is not empty
        if [ -n "${{ inputs.config }}" ]; then
          CMD_ARGS+=("--config" "${{ inputs.config }}")
        fi

        # CLI Mode: File and Image (only if provided)
        if [ -n "${{ inputs.file }}" ]; then
          CMD_ARGS+=("--file" "${{ inputs.file }}")
        fi
        if [ -n "${{ inputs.image }}" ]; then
          CMD_ARGS+=("--image" "${{ inputs.image }}")
        fi

        # Boolean Flags
        if [ "${{ inputs.dry-run }}" == "true" ]; then
          CMD_ARGS+=("--dry-run")
        fi
        if [ "${{ inputs.nomoji }}" == "true" ]; then
          CMD_ARGS+=("--nomoji")
        fi
        if [ "${{ inputs.ignore-errors }}" == "true" ]; then
          CMD_ARGS+=("--ignore-errors")
        fi
        if [ "${{ inputs.verbose }}" == "true" ]; then
          CMD_ARGS+=("--verbose")
        fi

        # Execute
        echo "Running: dock-docs ${CMD_ARGS[*]}"
        dock-docs "${CMD_ARGS[@]}"