name: 'Docker Documentation Generator'
description: 'Automatically generate README documentation from Dockerfiles'
author: 'northcutted'
inputs:
  config:
    description: 'Path to configuration file'
    default: 'dock-docs.yaml'
  output:
    description: 'Output file path'
    default: 'README.md'
runs:
  using: 'composite'
  steps:
    - name: Run dock-docs
      shell: bash
      run: |
        # 1. Open up socket permissions (Safe on ephemeral GH runners)
        # This bypasses the need for --group-add or finding the specific GID
        sudo chmod 666 /var/run/docker.sock
        
        # 2. Run container as the CURRENT user (id -u)
        # This ensures the generated README.md is owned by the runner, not root.
        docker run --rm \
          --user $(id -u):$(id -g) \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -v ${{ github.workspace }}:/github/workspace \
          -w /github/workspace \
          ghcr.io/northcutted/dock-docs:latest \
          --config ${{ inputs.config }} \
          --output ${{ inputs.output }}