name: 'Docker Documentation Generator'
description: 'Automatically generate README documentation from Dockerfiles using dock-docs'
author: 'northcutted'
branding:
  icon: 'file-text'
  color: 'blue'

inputs:
  version:
    description: 'Version of dock-docs to use (e.g., v1.0.0). Defaults to latest.'
    default: 'latest'
    required: false
  
  # --- Configuration Inputs ---
  config:
    description: 'Path to configuration file. Enables YAML Mode if present.'
    default: 'dock-docs.yaml'
    required: false
  output:
    description: 'Output file path.'
    default: 'README.md'
    required: false
  
  # --- Boolean Flags ---
  dry-run:
    description: 'Print output to stdout instead of modifying files.'
    default: 'false'
    required: false
  nomoji:
    description: 'Disable emojis in the output.'
    default: 'false'
    required: false
  ignore-errors:
    description: 'Ignore analysis errors and continue generation.'
    default: 'false'
    required: false
  verbose:
    description: 'Enable verbose logging for debugging.'
    default: 'false'
    required: false

  # --- CLI Mode Inputs (Mutually exclusive with config usually) ---
  file:
    description: 'Path to Dockerfile (CLI Mode only).'
    required: false
  image:
    description: 'Docker image tag to analyze (CLI Mode only).'
    required: false

runs:
  using: "composite"
  steps:
    # 1. Setup Tool Cache
    - name: Setup Tool Cache
      shell: bash
      run: |
        set -euo pipefail
        TOOL_DIR="$HOME/.dock-docs/bin"
        mkdir -p "$TOOL_DIR"
        echo "$TOOL_DIR" >> $GITHUB_PATH

    # 2. Install dock-docs
    - name: Install dock-docs
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
        INPUT_VERSION: ${{ inputs.version }}
        RUNNER_ARCH: ${{ runner.arch }}
      run: |
        set -euo pipefail
        TOOL_DIR="$HOME/.dock-docs/bin"
        
        # Map GitHub Runner OS/Arch to GoReleaser naming convention
        OS_NAME=$(uname -s) # Linux, Darwin
        if [ "$RUNNER_ARCH" = "ARM64" ]; then
          ARCH_NAME="arm64"
        else
          ARCH_NAME="x86_64"
        fi

        # Construct asset pattern (e.g., *_Linux_x86_64.tar.gz)
        ASSET_PATTERN="*_${OS_NAME}_${ARCH_NAME}.tar.gz"
        
        # Download via GH CLI
        if [ "$INPUT_VERSION" = "latest" ]; then
           gh release download --repo northcutted/dock-docs --pattern "$ASSET_PATTERN" --output "$TOOL_DIR/dock-docs.tar.gz" --clobber
        else
           gh release download "$INPUT_VERSION" --repo northcutted/dock-docs --pattern "$ASSET_PATTERN" --output "$TOOL_DIR/dock-docs.tar.gz" --clobber
        fi

        # Extract
        tar -xzf "$TOOL_DIR/dock-docs.tar.gz" -C "$TOOL_DIR" dock-docs
        rm "$TOOL_DIR/dock-docs.tar.gz"
        chmod +x "$TOOL_DIR/dock-docs"

    # 3. Install Dependencies (Syft, Grype, Dive) via dock-docs setup
    - name: Install Dependencies
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        set -euo pipefail
        TOOL_DIR="$HOME/.dock-docs/bin"
        "$TOOL_DIR/dock-docs" setup --dir "$TOOL_DIR"

    # 4. Run dock-docs with all flags
    - name: Run dock-docs
      shell: bash
      env:
        INPUT_OUTPUT: ${{ inputs.output }}
        INPUT_CONFIG: ${{ inputs.config }}
        INPUT_FILE: ${{ inputs.file }}
        INPUT_IMAGE: ${{ inputs.image }}
        INPUT_DRY_RUN: ${{ inputs.dry-run }}
        INPUT_NOMOJI: ${{ inputs.nomoji }}
        INPUT_IGNORE_ERRORS: ${{ inputs.ignore-errors }}
        INPUT_VERBOSE: ${{ inputs.verbose }}
      run: |
        set -euo pipefail
        # Build arguments array dynamically
        CMD_ARGS=()

        # Always add output
        CMD_ARGS+=("--output" "$INPUT_OUTPUT")

        # YAML Mode: Only add if input is not empty
        if [ -n "$INPUT_CONFIG" ]; then
          CMD_ARGS+=("--config" "$INPUT_CONFIG")
        fi

        # CLI Mode: File and Image (only if provided)
        if [ -n "${INPUT_FILE:-}" ]; then
          CMD_ARGS+=("--file" "$INPUT_FILE")
        fi
        if [ -n "${INPUT_IMAGE:-}" ]; then
          CMD_ARGS+=("--image" "$INPUT_IMAGE")
        fi

        # Boolean Flags
        if [ "$INPUT_DRY_RUN" == "true" ]; then
          CMD_ARGS+=("--dry-run")
        fi
        if [ "$INPUT_NOMOJI" == "true" ]; then
          CMD_ARGS+=("--nomoji")
        fi
        if [ "$INPUT_IGNORE_ERRORS" == "true" ]; then
          CMD_ARGS+=("--ignore-errors")
        fi
        if [ "$INPUT_VERBOSE" == "true" ]; then
          CMD_ARGS+=("--verbose")
        fi

        # Execute
        echo "Running: dock-docs ${CMD_ARGS[*]}"
        dock-docs "${CMD_ARGS[@]}"